name: 1 Deploy Dev to VPS

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: 🧱 Build app (dev)
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout código
        uses: actions/checkout@v3

      - name: ☕ Instalar JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: 🔨 Build com Maven
        working-directory: app
        run: mvn clean package -DskipTests

      - name: 📂 Verificar se o JAR foi gerado
        run: ls -lh app/target/

      - name: 📦 Salvar artefato gerado dinamicamente
        uses: actions/upload-artifact@v4
        with:
          name: app-jar-dev
          path: app/target/*.jar  # detecta automaticamente qualquer JAR gerado

  upload:
    name: 🚀 Enviar JAR (dev) para VPS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 📥 Baixar artefato
        uses: actions/download-artifact@v4
        with:
          name: app-jar-dev

      - name: 📂 Verificar JAR baixado
        run: ls -lh

      - name: 🔑 Instalar sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: 🔄 Limpeza de arquivos antigos para novo recebimento
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" \
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
          'rm -rf /home/ubuntu/develop/*'

      - name: 📤 Copiar JAR para VPS
        run: |
          FILE_NAME=$(ls *.jar)
          echo "Arquivo detectado: $FILE_NAME"

          sshpass -p "${{ secrets.VPS_PASSWORD }}" \
          ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no -o StrictHostKeyChecking=no \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p /home/ubuntu/develop"

          sshpass -p "${{ secrets.VPS_PASSWORD }}" \
          scp -o PreferredAuthentications=password -o PubkeyAuthentication=no -o StrictHostKeyChecking=no \
          "$FILE_NAME" \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/ubuntu/develop/

      - name: 📝 Salvar nome do arquivo para o próximo job
        run: |
          FILE_NAME=$(ls *.jar)
          echo "JAR_NAME=$FILE_NAME" >> $GITHUB_ENV

  shutdown:
    name: 🛑 Parar instância antiga (dev)
    runs-on: ubuntu-latest
    needs: upload

    steps:
      - name: 🔻 Finalizar processo antigo (porta 8081 e sessão tmux)
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
          'PID=$(lsof -ti:8081); \
           if [ -n "$PID" ]; then kill -9 $PID; fi; \
           if tmux has-session -t app-dev 2>/dev/null; then tmux kill-session -t app-dev; fi'


  deploy:
    name: 🚦 Iniciar aplicação via tmux (dev)
    runs-on: ubuntu-latest
    needs: shutdown

    steps:
      - name: 🚀 Iniciar aplicação na VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
          'JAR_NAME=$(ls /home/ubuntu/develop/*.jar | xargs -n1 basename); \
           cd /home/ubuntu/develop && \
           tmux new-session -d -s app-dev "java -jar $JAR_NAME --spring.profiles.active=dev"'

  health-check:
    name: 🩺 Verificar aplicação (dev)
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: ⏳ Esperar aplicação subir
        run: sleep 20

      - name: ✅ Verificar status
        run: |
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.VPS_HOST }}:8081/actuator/health)
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "❌ Falha no Health Check. Status: $HTTP_STATUS"
            exit 1
          else
            echo "✅ Aplicação está no ar (200 OK)"
          fi