name: 3 Deploy to Production VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 🧱 Build app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build com Maven
        working-directory: app
        run: mvn clean package -DskipTests

      - name: Renomear JAR gerado dinamicamente
        run: |
          JAR_FILE=$(find app/target -type f -name "*.jar" | head -n 1)
          echo "JAR encontrado: $JAR_FILE"
          cp "$JAR_FILE" app/target/app.jar
          echo "$(basename $JAR_FILE)" > jar_name.txt

      - name: Verificar se o JAR foi gerado
        run: ls -lh app/target/

      - name: Salvar artefato JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: app/target/app.jar

      - name: Salvar nome do JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-name
          path: jar_name.txt

  upload:
    name: 🚀 Enviar JAR para VPS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Baixar artefato JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar

      - name: Instalar sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Criar diretório de deploy e enviar JAR
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p /home/ubuntu/production"

          sshpass -p "${{ secrets.VPS_PASSWORD }}" scp -o StrictHostKeyChecking=no \
            app.jar ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/ubuntu/production/app.jar

  shutdown:
    name: 🛑 Parar instância antiga
    runs-on: ubuntu-latest
    needs: upload

    steps:
      - name: Finalizar processo antigo
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            'PID=$(lsof -ti:8080); if [ -n "$PID" ]; then kill -9 $PID; fi'

  deploy:
    name: 🚦 Iniciar aplicação via tmux
    runs-on: ubuntu-latest
    needs: shutdown

    steps:
      - name: Iniciar aplicação
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
              export DATASOURCE_URL='${{ secrets.DATASOURCE_URL }}'
              export DATASOURCE_USERNAME='${{ secrets.DATASOURCE_USERNAME }}'
              export DATASOURCE_PASSWORD='${{ secrets.DATASOURCE_PASSWORD }}'
              tmux new-session -d -s app-prod 'bash -c \"java -jar /home/ubuntu/production/app.jar --spring.profiles.active=prod\"'
            "

  health-check:
    name: 🩺 Verificar aplicação
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Esperar aplicação subir
        run: sleep 15

      - name: Verificar status
        run: |
          HTTP_STATUS=$(curl -s -o /dev/null --max-time 10 -w "%{http_code}" http://${{ secrets.VPS_HOST }}:8080/actuator/health)
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "❌ Health check falhou com status: $HTTP_STATUS"
            exit 1
          else
            echo "✅ Aplicação no ar (200 OK)"
          fi

  logs:
    name: 📜 Logs
    runs-on: ubuntu-latest
    needs: health-check

    steps:
      - name: Ler logs da aplicação
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
          'tail -n 200 /home/ubuntu/production/logs/app.log || echo "⚠️ Arquivo de log não encontrado"'
