name: 3.1 Rollback da Produção

on:
  workflow_dispatch:

jobs:
  rollback:
    name: 🔙 Rollback para versão anterior
    runs-on: ubuntu-latest

    steps:
      - name: Instalar sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Executar rollback na VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} '
              echo "➡️ Encerrando aplicação atual..."
              PID=$(lsof -ti:8080)
              if [ -n "$PID" ]; then kill -9 $PID; fi

              echo "🔁 Localizando o último backup..."
              cd /home/ubuntu/production/backups
              LAST_BACKUP=$(ls -t app-*.jar 2>/dev/null | head -n 1)

              if [ -n "$LAST_BACKUP" ]; then
                echo "📦 Backup encontrado: $LAST_BACKUP"
                cp "$LAST_BACKUP" ../app-latest.jar

                echo "🚀 Iniciando rollback..."
                cd ../
                tmux kill-session -t app-prod 2>/dev/null || true
                tmux new-session -d -s app-prod "export DATASOURCE_URL=${{ secrets.DATASOURCE_URL }} && \
                                                 export DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }} && \
                                                 export DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }} && \
                                                 java -jar app-latest.jar --spring.profiles.active=prod"
              else
                echo "⚠️ Nenhum backup encontrado para rollback."
              fi
            '
